### ISSUE TITLE
Failure during file creation does not report error, but panics.

### ISSUE THREAD

**Issue by martin-kolarik** [outersky/simple_excel_writer#14]
Thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: Other, message: "Proces nemá přístup k souboru, neboť jej právě využívá jiný proces." }', ...\simple_excel_writer-0.1.7\src\workbook.rs:128:52

IMO there unwrap should be replaced with ?.

**Comment by CadeLilley** [comment]
Does anyone have a solution to this?

**Comment by cfsamson** [comment]
Do you have a way to reproduce the error? I would assume the error is caused by this unwrap: https://github.com/outersky/simple_excel_writer/blob/8af5a2b6b5f1c0c6946287608e3376cc94270238/src/workbook.rs#L128

It should be an easy fix since `close` already returns a `Result`, but without a stack trace or a reproducible example it's not easy to be sure that we fix the right thing.

**Comment by CadeLilley** [comment]
> It should be an easy fix since `close` already returns a `Result`, but without a stack trace or a reproducible example it's not easy to be sure that we fix the right thing.

I've actually resolved my issue. It wasn't with your program, just my own user error. Thank you for getting back to me so quickly. I appreciate your tool!

**Comment by cfsamson** [comment]
@CadeLilley Great it worked out. Just so I don't take credit for anything, this is not my program, just one I'm using myself and am interested in.
